module.exports = {
	extends: [],
	plugins: ['react', 'react-hooks'],
	rules: {
		'react/button-has-type': 'error',
		'react/display-name': 'error',
		'react/hook-use-state': 'error',
		'react/jsx-key': 'error',
		'react/jsx-no-comment-textnodes': 'error',
		'react/jsx-no-duplicate-props': 'error',
		'react/jsx-no-target-blank': 'error',
		'react/jsx-no-undef': 'error',
		'react/jsx-uses-vars': 'error',
		'react/no-danger-with-children': 'error',
		'react/no-deprecated': 'error',
		'react/no-direct-mutation-state': 'error',
		'react/no-find-dom-node': 'error',
		'react/no-is-mounted': 'error',
		'react/no-render-return-value': 'error',
		'react/no-string-refs': 'error',
		'react/no-this-in-sfc': 'error',
		'react/no-unknown-property': 'error',
		'react/no-unsafe': 'error',
		'react/no-unstable-nested-components': 'error',
		'react/prop-types': 'error',
		'react/require-render-return': 'error',
		'react/void-dom-elements-no-children': 'error',

		'react-hooks/rules-of-hooks': 'error',
		'react-hooks/exhaustive-deps': 'warn',
	},
};
