module.exports = {
  extends: [],
  plugins: ['unicorn', '@typescript-eslint'],
  rules: {
    // ESLint
    'getter-return': 'error',
    'no-debugger': 'error',
    'no-empty-static-block': 'error',
    'no-empty': 'error',
    'no-eval': 'error',
    'no-extra-boolean-cast': 'error',
    'no-inner-declarations': 'error',
    'no-irregular-whitespace': 'error',
    'no-labels': 'error',
    'no-multi-assign': 'error',
    'no-regex-spaces': 'error',
    'no-return-assign': 'error',
    'no-sequences': 'error',
    'no-setter-return': 'error',
    'no-throw-literal': 'error',
    'no-useless-backreference': 'error',
    'no-useless-catch': 'error',
    'no-useless-escape': 'error',
    'no-useless-rename': 'error',
    'no-var': 'error',
    'one-var': ['error', 'never'],
    'prefer-const': 'error',
    'prefer-promise-reject-errors': 'error',

    // Unicorn
    'unicorn/consistent-function-scoping': 'error',
    'unicorn/error-message': 'error',
    'unicorn/new-for-builtins': 'error',
    'unicorn/no-array-method-this-argument': 'error',
    'unicorn/no-typeof-undefined': 'error',
    'unicorn/no-useless-fallback-in-spread': 'error',
    'unicorn/no-useless-promise-resolve-reject': 'error',
    'unicorn/no-useless-spread': 'error',
    'unicorn/no-useless-switch-case': 'error',
    'unicorn/prefer-prototype-methods': 'error',
    'unicorn/require-array-join-separator': 'error',
    'unicorn/require-number-to-fixed-digits-argument': 'error',
  },
  overrides: [
    {
      files: ['*.ts', '*.tsx'],
      rules: {
        '@typescript-eslint/adjacent-overload-signatures': 'error',
        '@typescript-eslint/ban-ts-comment': [
          'error',
          {
            'ts-expect-error': 'allow-with-description',
            'ts-ignore': true,
            'ts-nocheck': true,
            'ts-check': false,
          },
        ],
        '@typescript-eslint/no-extra-non-null-assertion': 'error',
        '@typescript-eslint/no-inferrable-types': 'error',
        '@typescript-eslint/no-non-null-asserted-nullish-coalescing': 'error',
        '@typescript-eslint/no-non-null-asserted-optional-chain': 'error',
        '@typescript-eslint/no-this-alias': 'error',
        '@typescript-eslint/prefer-as-const': 'error',
        '@typescript-eslint/prefer-namespace-keyword': 'error',
        '@typescript-eslint/prefer-optional-chain': 'error',
        '@typescript-eslint/prefer-ts-expect-error': 'error',

        'no-throw-literal': 'off',
        '@typescript-eslint/no-throw-literal': 'error',
      },
    },
  ],
};
